# Simple workflow for deploying static content to GitHub Pages
name: Build and Deploy static content to Pages

on:
  # Runs on pushes targeting the default branch
  push:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Single deploy job since we're just deploying
  Build:
    runs-on: ubuntu-latest
    container:
      image: shubhamdpatil/esp-matter:latest
    strategy:
      matrix:
        build-dir: ['connectedhomeip/connectedhomeip/examples/lighting-app/esp32', 'connectedhomeip/connectedhomeip/examples/all-clusters-app/esp32', 'examples/light', 'examples/light_switch', 'examples/zap_light']
        targets: ['esp32', 'esp32c3']

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: idf stuff
        run: |
          rm -rf connectedhomeip/connectedhomeip
          ln -s $CHIP_PATH connectedhomeip
          mkdir -p images
          echo "## Images" > images/README.md

      - name: build application
        run: |
          export ESP_MATTER_PATH=$PWD
          . $IDF_PATH/export.sh
          . $ESP_MATTER_PATH/export.sh
          cd ${{matrix.build-dir}}
          idf.py set-target ${{matrix.targets}} build
          BL_OFFSET=`grep CONFIG_BOOTLOADER_OFFSET_IN_FLASH sdkconfig | awk -F = '{print $2}'`
          PT_OFFSET=`grep CONFIG_PARTITION_TABLE_OFFSET sdkconfig | awk -F = '{print $2}'`
          APP_OFFSET=`gen_esp32part.py build/partition_table/partition-table.bin 2>/dev/null | grep ota_0 | awk -F , '{print $4}'`
          TARGET_CHIP=`cat build/project_description.json | python3 -c 'import sys,json; print(json.load(sys.stdin)["target"])'`
          APP_BIN=`cat build/project_description.json | python3 -c 'import sys,json; print(json.load(sys.stdin)["app_bin"])'`
          esptool.py --chip $TARGET_CHIP merge_bin -o "$ESP_MATTER_PATH/images/$TARGET_CHIP"_"$APP_BIN" --flash_size 4MB $BL_OFFSET build/bootloader/bootloader.bin $PT_OFFSET build/partition_table/partition-table.bin $APP_OFFSET build/$APP_BIN
          echo "["$TARGET_CHIP"_"$APP_BIN"]("./$TARGET_CHIP"_"$APP_BIN")"  >> $ESP_MATTER_PATH/images/README.md
          echo "" >> $ESP_MATTER_PATH/images/README.md

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'images/*.bin'

  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    container:
      image: shubhamdpatil/esp-matter:latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: make image dir
      - run: mkdir -p images

      - name: Download builds
      - uses: actions/download-artifact@v3
        with:
          path: images/

      - name: generate launchpad config
        run: |
          ls
          cd images
          ls
          ../tools/launchpad/generate_launchpad_config.sh

      - name: Setup Pages
        uses: actions/configure-pages@v2
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: 'images/'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
