name: mfg tool release

on:
  push:
    paths:
      - tools/mfg_tool
      - .github/workflows/upload_mfg_tool_to_pypi.yaml
    branches:
      - py_mfg_tool

jobs:
  build_and_upload:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Print versions
      run: |
        cd tools/mfg_tool
        export PV=$(curl https://test.pypi.org/pypi/esp-matter-mfg-tool/json 2>/dev/null | jq -r '.info.version')
        export CV=$(python setup.py --version 2>/dev/null)
        UPLOAD=(python3 -c 'from packaging import version; import os; print(version.parse(os.environ["PV"]) < version.parse(os.environ["CV"]))')
        echo "SHALL_UPLOAD=$UPLOAD" >> $GITHUB_ENV

    - name: Install pypa/build
      run: |
        python3 -m pip install build --user

    - name: Build a binary wheel and a source tarball
      run: |
        cd tools/mfg_tool
        python3 -m build --sdist --wheel --outdir dist/ .

    - name: Publish distribution 📦 to Test PyPI
      if: ${{ env.SHALL_UPLOAD }} == 'True'
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.TEST_PYPI_TOKEN }}
        repository-url: https://test.pypi.org/legacy/
        packages-dir: tools/mfg_tool/dist
